// copyright dbosoft GmbH / licensed under MIT license
// based on sample code by Microsoft Windows SDK samples 
// https://github.com/microsoft/Windows-classic-samples/blob/master/Samples/Win7Samples/winbase/imapi/interop/IMAPIv2.cs


// ReSharper disable InconsistentNaming
// ReSharper disable UnusedMember.Global
namespace Dbosoft.CloudInit.ConfigDrive.Interop
{
    public enum IMAPI_FEATURE_PAGE_TYPE
    {
        IMAPI_FEATURE_PAGE_TYPE_PROFILE_LIST = 0,
        IMAPI_FEATURE_PAGE_TYPE_CORE = 1,
        IMAPI_FEATURE_PAGE_TYPE_MORPHING = 2,
        IMAPI_FEATURE_PAGE_TYPE_REMOVABLE_MEDIUM = 3,
        IMAPI_FEATURE_PAGE_TYPE_WRITE_PROTECT = 4,
        IMAPI_FEATURE_PAGE_TYPE_RANDOMLY_READABLE = 16,
        IMAPI_FEATURE_PAGE_TYPE_CD_MULTIREAD = 29,
        IMAPI_FEATURE_PAGE_TYPE_CD_READ = 30,
        IMAPI_FEATURE_PAGE_TYPE_DVD_READ = 31,
        IMAPI_FEATURE_PAGE_TYPE_RANDOMLY_WRITABLE = 32,
        IMAPI_FEATURE_PAGE_TYPE_INCREMENTAL_STREAMING_WRITABLE = 33,
        IMAPI_FEATURE_PAGE_TYPE_SECTOR_ERASABLE = 34,
        IMAPI_FEATURE_PAGE_TYPE_FORMATTABLE = 35,
        IMAPI_FEATURE_PAGE_TYPE_HARDWARE_DEFECT_MANAGEMENT = 36,
        IMAPI_FEATURE_PAGE_TYPE_WRITE_ONCE = 37,
        IMAPI_FEATURE_PAGE_TYPE_RESTRICTED_OVERWRITE = 38,
        IMAPI_FEATURE_PAGE_TYPE_CDRW_CAV_WRITE = 39,
        IMAPI_FEATURE_PAGE_TYPE_MRW = 40,
        IMAPI_FEATURE_PAGE_TYPE_ENHANCED_DEFECT_REPORTING = 41,
        IMAPI_FEATURE_PAGE_TYPE_DVD_PLUS_RW = 42,
        IMAPI_FEATURE_PAGE_TYPE_DVD_PLUS_R = 43,
        IMAPI_FEATURE_PAGE_TYPE_RIGID_RESTRICTED_OVERWRITE = 44,
        IMAPI_FEATURE_PAGE_TYPE_CD_TRACK_AT_ONCE = 45,
        IMAPI_FEATURE_PAGE_TYPE_CD_MASTERING = 46,
        IMAPI_FEATURE_PAGE_TYPE_DVD_DASH_WRITE = 47,
        IMAPI_FEATURE_PAGE_TYPE_DOUBLE_DENSITY_CD_READ = 48,
        IMAPI_FEATURE_PAGE_TYPE_DOUBLE_DENSITY_CD_R_WRITE = 49,
        IMAPI_FEATURE_PAGE_TYPE_DOUBLE_DENSITY_CD_RW_WRITE = 50,
        IMAPI_FEATURE_PAGE_TYPE_LAYER_JUMP_RECORDING = 51,
        IMAPI_FEATURE_PAGE_TYPE_CD_RW_MEDIA_WRITE_SUPPORT = 55,
        IMAPI_FEATURE_PAGE_TYPE_BD_PSEUDO_OVERWRITE = 56,
        IMAPI_FEATURE_PAGE_TYPE_DVD_PLUS_R_DUAL_LAYER = 59,
        IMAPI_FEATURE_PAGE_TYPE_BD_READ = 64,
        IMAPI_FEATURE_PAGE_TYPE_BD_WRITE = 65,
        IMAPI_FEATURE_PAGE_TYPE_HD_DVD_READ = 80,
        IMAPI_FEATURE_PAGE_TYPE_HD_DVD_WRITE = 81,
        IMAPI_FEATURE_PAGE_TYPE_POWER_MANAGEMENT = 256,
        IMAPI_FEATURE_PAGE_TYPE_SMART = 257,
        IMAPI_FEATURE_PAGE_TYPE_EMBEDDED_CHANGER = 258,
        IMAPI_FEATURE_PAGE_TYPE_CD_ANALOG_PLAY = 259,
        IMAPI_FEATURE_PAGE_TYPE_MICROCODE_UPDATE = 260,
        IMAPI_FEATURE_PAGE_TYPE_TIMEOUT = 261,
        IMAPI_FEATURE_PAGE_TYPE_DVD_CSS = 262,
        IMAPI_FEATURE_PAGE_TYPE_REAL_TIME_STREAMING = 263,
        IMAPI_FEATURE_PAGE_TYPE_LOGICAL_UNIT_SERIAL_NUMBER = 264,
        IMAPI_FEATURE_PAGE_TYPE_MEDIA_SERIAL_NUMBER = 265,
        IMAPI_FEATURE_PAGE_TYPE_DISC_CONTROL_BLOCKS = 266,
        IMAPI_FEATURE_PAGE_TYPE_DVD_CPRM = 267,
        IMAPI_FEATURE_PAGE_TYPE_FIRMWARE_INFORMATION = 268,
        IMAPI_FEATURE_PAGE_TYPE_AACS = 269,
        IMAPI_FEATURE_PAGE_TYPE_VCPS = 272,
    }
}